services:
    grafana:
        image: grafana/grafana-oss:latest
        container_name: grafana
        # logging:
        #     driver: loki
        #     options:
        #         loki-url: "https://<user_id>:<password>@.../loki/api/v1/push"
        #         loki-retries: 2
        #         loki-max-backoff: 800ms
        #         loki-timeout: 1s
        #         keep-file: "true"
        #         mode: "non-blocking"
        ports:
            - "${GRAFANA_PORT:-3000}:3000"
        environment:
            - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
        volumes:
            - "grafana_storage:/var/lib/grafana"
        restart: unless-stopped
    loki:
        image: grafana/loki:latest
        container_name: loki
        command: "-config.file=/etc/loki/local-config.yaml -config.expand-env=true"
        volumes:
            - $PWD/loki-config.yml:/etc/loki/local-config.yaml:ro
        ports:
            - "${LOKI_PORT:-3100}:3100"
        restart: unless-stopped

volumes:
  grafana_storage: {}
