services:
    grafana:
        image: grafana/grafana-oss:latest
        container_name: grafana
        ports:
            - "${GRAFANA_PORT:-3000}:3000"
        environment:
            - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
        volumes:
            - "grafana_storage:/var/lib/grafana"
        restart: unless-stopped

volumes:
  grafana_storage: {}
