auth_enabled: true

server:
    http_listen_port: 3100

common:
    ring:
        instance_addr: 127.0.0.1
        kvstore:
            store: inmemory
    replication_factor: 1
    path_prefix: /loki

schema_config:
    configs:
    - from: "2023-06-15"
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
    tsdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/index_cache
    aws:
        bucketnames: ${S3_BUCKET_NAMES}
        endpoint: ${S3_ENDPOINT}
        region: ${S3_REGION}
        access_key_id: ${S3_ACCESS_KEY_ID}
        secret_access_key: ${S3_SECRET_ACCESS_KEY}
        insecure: false
        s3forcepathstyle: true
