auth_enabled: true

server:
    http_listen_port: 3100

common:
    instance_addr: 127.0.0.1
    path_prefix: /tmp/loki
    replication_factor: 1
    ring:
        kvstore:
            store: inmemory

querier:
    multi_tenant_queries_enabled: true

schema_config:
    configs:
    - from: 2020-05-15
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
    tsdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/index_cache
    aws:
        bucketnames: ${S3_BUCKET_NAMES}
        endpoint: ${S3_ENDPOINT}
        region: ${S3_REGION}
        access_key_id: ${S3_ACCESS_KEY_ID}
        secret_access_key: ${S3_SECRET_ACCESS_KEY}
        insecure: false
        s3forcepathstyle: true
